services:
  note-app:
    build: .
    container_name: note-app
    restart: always
    environment:
      - VIRTUAL_HOST=note.${S_DOMAIN}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=note.${S_DOMAIN}
      - DB_PATH=/data/notes.db
    volumes:
      - note-data:/data
    expose:
      - "80"

volumes:
  note-data:
