services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    environment:
      - DEFAULT_EMAIL=${S_EMAIL}
    network_mode: "host"
    restart: always
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ${S_CONTAINER_FOLDER_ACTIVE}/nginx-proxy/vhost:/etc/nginx/vhost.d
      - ${S_CONTAINER_FOLDER_ACTIVE}/nginx-proxy/html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=${S_EMAIL}
    restart: always
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ${S_CONTAINER_FOLDER_ACTIVE}/nginx-proxy/vhost:/etc/nginx/vhost.d
      - ${S_CONTAINER_FOLDER_ACTIVE}/nginx-proxy/html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:rw
      - ${S_CONTAINER_FOLDER_ACTIVE}/nginx-proxy/acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
