services:
  todo-app:
    build: .
    container_name: todo-app-issue9
    restart: always
    environment:
      - VIRTUAL_HOST=todo-issue9.${S_DOMAIN}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=todo-issue9.${S_DOMAIN}
    expose:
      - "80"
