services:
  todo-app:
    build: .
    container_name: todo-app
    restart: always
    environment:
      - VIRTUAL_HOST=todo.${S_DOMAIN}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=todo.${S_DOMAIN}
    expose:
      - "80"
