services:
  todo-app:
    build: .
    container_name: todo-app
    restart: always
    environment:
      - VIRTUAL_HOST=todo.${S_DOMAIN}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=todo.${S_DOMAIN}
      - DB_PATH=/data/todos.db
      - SESSION_SECRET=${SESSION_SECRET:-}
    volumes:
      - todo-data:/data
    expose:
      - "80"

volumes:
  todo-data:
